# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class mainUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 100)
        Form.setMinimumSize(QtCore.QSize(340, 100))
        Form.setMaximumSize(QtCore.QSize(340, 100))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 324, 78))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_path.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout.addWidget(self.lineEdit_path)
        self.ChooseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ChooseButton.setObjectName("ChooseButton")
        self.horizontalLayout.addWidget(self.ChooseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_time = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.horizontalLayout_2.addWidget(self.lineEdit_time)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.SaveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout_2.addWidget(self.SaveButton)
        self.GenerateButton = QtWidgets.QPushButton(self.layoutWidget)
        self.GenerateButton.setObjectName("GenerateButton")
        self.horizontalLayout_2.addWidget(self.GenerateButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BreakButton = QtWidgets.QPushButton(self.layoutWidget)
        self.BreakButton.setObjectName("BreakButton")
        self.horizontalLayout_3.addWidget(self.BreakButton)
        self.LinkButton = QtWidgets.QPushButton(self.layoutWidget)
        self.LinkButton.setObjectName("LinkButton")
        self.horizontalLayout_3.addWidget(self.LinkButton)
        self.StartButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout_3.addWidget(self.StartButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Offline tools"))
        self.label.setText(_translate("Form", "游戏路径"))
        self.ChooseButton.setText(_translate("Form", "选择"))
        self.label_2.setText(_translate("Form", "重连延时"))
        self.label_3.setText(_translate("Form", "秒"))
        self.SaveButton.setText(_translate("Form", "保存配置"))
        self.GenerateButton.setText(_translate("Form", "程序生成"))
        self.BreakButton.setText(_translate("Form", "断网"))
        self.LinkButton.setText(_translate("Form", "联网"))
        self.StartButton.setText(_translate("Form", "一键断联"))
